

Courses = {

    "4BSC01":{

        "Departments":["Mathematical Science","Computer Scince"],
        "course name":"APPLIED MATHEMATICS AND COMPUTER SCIENCE",
        "Total Credits":416,
        "Module codes":["4AMT111","4MTH111","4CPS111","4CPS121","4AMT122","4MTH112","4CPS112","4CPS122","4AMT211","4MTH221","4CPS211",
                         "4CPS231","4AMT212","4MTH222","4CPS212","4CPS232","4AMT331","4AMT321","4CPS311","4CPS321","4AMT312","4AMT322",
                         "4CPS312","4CPS322"],
        "Module Names":["DISCRETE MATHEMATICS",
                         "CALCULUS I",
                         "INTRODUCTORY COMPUTING",
                         "COMPUTER LITERACY I ",
                         "FURTHER DISCRETE MATHEMATICS",
                         "CALCULUS II ",
                         "INTRO TO SYSTEMS PROGRAMMING",
                         "COMPUTER LITERACY II",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "ADVANCED CALCULUS",
                         "DATA STRUCTURES AND ALGORITHMS",
                         "COMPUTER COMMUNICATIONS & NETWORKS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "SOFTWARE ENGINEERING",
                         "DATABASE INFORMATION MANAGEMENT I",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "ADVANCED PROGRAMMING TECHNIQUES",
                         "SYSTEMS PROGRAMMING (OS & COMPILERS)",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS",
                         "DISTRIBUTED SYSTEMS DEVELOPMENT",
                         "FINAL YEAR PROJECT"],
        "Elective modules":["CLASSICAL MECHANICS & PROPERTIES OF MATTER",
                           " ELEMENTARY STATISTICS FOR SCIENCE STUDENTS",
                           "ELECTROMAGNETISM, NUCLEAR & MODERN PHYSICS",
                           "STATISTICS FOR SCIENCE STUDENTS"],
        "Elective codes":["4PHY111","4STT111","4PHY112","4STT112"]
    },

"4BSC02":{
        "Departments":["MATHEMATICAL SCIENCES","HYDROLOGY"],
        "course name":"APPLIED MATHEMATICS AND HYDROLOGY",
        "Total Credits":416,
        "Module codes":["4GES111","4MTH111","4AMT111","4PHY111","4CPS121","4HYD112","4MTH112","4AMT122","4STT122","4CPS122",
                         "4HYD211","4MTH221","4AMT211","4GES211","4HYD212","4MTH222","4AMT212","4HYD222",
                         "4HYD311","4HYD321","4AMT331","4AMT321","4HYD332","4HYD342","4AMT312","4AMT322"],
        "Module Names":["INTRO TO PHYSICAL & ENVIRONMENTAL GEOGRAPHY",
                         "CALCULUS I",
                         "DISCRETE MATHEMATICS",
                         "CLASSICAL MECHANICS AND PROPERTIES OF MATTER",
                         "COMPUTER LITERACY I",
                         "INTRO TO GEOLOGY",
                         "CALCULUS II",
                         "FURTHER DISCRETE MATHEMATICS",
                         "ELEMENTARY STATISTICS FOR COMMERCE STUDENTS",
                         "COMPUTER LITERACY II",
                         "INTRO TO SURFACE WATER HYDROLOGY",
                         "ADVANCED CALCULUS",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "GLOBAL LANDFORMS & CARTOGRAPHY",
                         "INTRO TO SUBSURFACE HYDROLOGY",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "GEOGRAPHICAL INFORMATION SYSTEMS",
                         "SURFACE WATER HYDROLOGY",
                         "GROUNDWATER HYDROLOGY",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "HYDROLOGICAL MODELLING",
                         "WATER RESOURCES MANAGEMENT",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS"],
        "Elective modules":[],
        "Elective codes":[]
    },
"4BSC03":{
        "Departments":["MATHEMATICAL SCIENCES"],
        "course name":"APPLIED MATHEMATICS AND MATHEMATICS",
        "Total Credits":416,
        "Module codes":["4MTH111","4AMT111","4CPS121","4AMT122","4MTH112","4CPS112",
                         "4CPS122","4AMT211","4MTH221","4AMT212","4MTH222","4AMT331",
                         "4AMT321","4MTH311","4MTH321","4AMT312","4AMT322","4MTH312","4MTH322"],
        "Module Names":["CALCULUS I",
                         "DISCRETE MATHEMATICS",
                         "COMPUTER LITERACY I",
                         "FURTHER DISCRETE MATHEMATICS",
                         "CALCULUS II",
                         "INTRO TO SYSTEMS PROGRAMMING",
                         "COMPUTER LITERACY II",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "ADVANCED CALCULUS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "ABSTRACT ALGEBRA",
                         "REAL ANALYSIS",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS",
                         "GRAPH THEORY",
                         "COMPLEX ANALYSIS"],
        "Elective modules":["INTRODUCTORY COMPUTING",
                           "CLASSICAL MECHANICS & MECHANICS & PROPERTIES OF MATTER",
                           "GENERAL CHEMISTRY 111",
                            "ELECTROMAGNETISM,NUCLEAR & MODERN PHYSICS",
                          "GENERAL CHEMISTRY 112",
                          "DATA STRUCTURES AND ALGORITHMS",
                          "MECHANICS SPECIAL RELATIVITY & PROPERTIES OF MATTER",
                          "DISTRIBUTION THEORY",
                          "COMPUTER COMMUNICATIONS NETWORKS",
                          "ANALYTICAL & INORGANIC CHEMISTRY 2",
                          "SOFTWARE ENGINEERING",
                          "MODERN PHYSICS,PHOTONICS AND WAVES",
                          "DATABASE INFORMATION MANAGEMENT I",
                          "ORGANIC & PHYSICAL CHEMISTRY 2"],
        "Elective codes":["4CPS111","4PHY111","4CHM111","4PHY112","4CHM112","4CPS211","4PHY211","4STT211","4CPS231","4CHM211","4CPS212","4PHY212","4CPS232","4CHM212"]
    },
"4BSC04":{
        "Departments":["MATHEMATICAL SCIENCES","PHYSICS & ENGINEERING"],
        "course name":"APPLIED MATHEMATICS AND PHYSICS",
        "Total Credits":416,
        "Modules codes":["4MTH111","4AMT111","4PHY111","4CPS121","4AMT122","4MTH112","4PHY112",
                         "4CPS122","4AMT211","4MTH221","4PHY211","4AMT212","4MTH222","4PHY212",
                         "4PHY222","4AMT331","4AMT321","4PHY311","4PHY321","4AMT312","4AMT322",
                         "4PHY312","4PHY322"],
        "Modules Names":["CALCULUS I","DISCRETE MATHEMATICS","CLASSICAL MECHANICS & PROPERTIES OF MATTER","COMPUTER LITERACY I","FURTHER DISCRETE MATHEMATICS","CALCULUS II ",
                         "ELECTROMAGNETISM, NUCLEAR & MODERN PHYSICS","COMPUTER LITERACY II ","DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING","ADVANCED CALCULUS","MECHANICS SPECIAL RELATIVITY & PROPERTIES OF MATTER",
                         "INTRO TO OPERATIONS RESEARCH","LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS","MODERN PHYSICS, PHOTONICS & WAVES","ELECTROMAGNETISM","TENSOR ANALYSIS","APPLIED MATHEMATICAL METHODS","QUANTUM AND STATISTICAL PHYSICS",
                         "ELECTRONIC CIRCUITS AND DEVICES","ADVANCED CLASSICAL MECHANICS","NUMERICAL METHODS ","NUCLEAR PHYSICS AND APPLICATIONS","SOLID STATE PHYSICS & MATERIAL SCIENCE"],
        "Elective modules":["INTRODUCTORY COMPUTING","GENERAL CHEMISTRY 111","INTRO TO SYSTEMS PROGRAMMING","ANALYTICAL & INORGANIC CHEMISTRY 2","DATA STRUCTURES AND ALGORITHMS","ANALYTICAL & INORGANIC CHEMISTRY 2"],
        "Elective codes":["4CPS111","4CHM111","4CPS112","4CHM112","4CPS211","4CHM211"]

    },
    "4BSC10":{
            "Departments":["BIOCHEMISTRY & MICROBIOLOGY","ZOOLOGY"],
            "course name":"BIOCHEMISTRY AND ZOOLOGY",
            "Total Credits":416,
            "Modules codes":["4CHM121","4PHY121","4BOT111","4ZOL111","4CPS121","4CHM122","4MTH122",
                             "4BOT112","4ZOL112","4CPS122","4BCH211","4MCB211","4ZOL211","4BCH212",
                             "4MCB212","4ZOL212","4BCH311","4BCH321","4ZOL311","4ZOL321","4BCH312",
                             "4BCH322","4ZOL312","4ZOL322"],
            "Modules Names":["BASIC CHEMISTRY 121","CLASSICAL MECHANICS & PROPERTIES OF MATTER(BIO)","INTRODUCTION TO PLANT PHYSIOLOGY & GENETICS","INTRO TO ZOOLOGY I","COMPUTER LITERACY I","BASIC CHEMISTRY 122","MATHS & STATS FOR EARTH & LIFE SCIENCES","PLANT MORPHOLOGY & TEXONOMY",
                             "INTRO TO ZOOLOGY II","COMPUTER LITERACY II","BIOMOLECULES & ENZYMOLOGY","PROKARYOTES CLASSIFICATION & MICROBIAL TECHNIQUES","ANIMAL ANATOMY & PHYSIOLOGY","METABOLISM","MICROBIAL GROWTH & MEDICAL MICROBIOLOGY","ANIMAL DIVERSITY","GENE EXPRESSION AND REPLICATION",
                             "METABOLIC REGULATION","ANIMAL ECOLOGY I","ECOPHYSIOLOGY & ECOTOXICOLOGY","RECOMBINANT DNA TECHNOLOGY","BIOCHEMISTRY OF NUTRITION","ANIMAL ECOLOGY II","RESEARCH DESIGN & APPLICATION"],
            "Elective module":["PROKARYOTES & EUKARYOTES","PLANT GROWTH & DEVELOPMENT","BIOCHEMISTRY:PRINCIPLES AND TECHNIQUES","PLANT ANATOMY & BIODIVERSITY"],
            "Elective codes":["4MCB221","4BOT211","4BCH222","4BOT212"]
        },
    "4BSC11":{
            "Departments":["BOTANY","GEOGRAPHY"],
            "course name":"BOTANY AND GEOGRAPHY",
            "Total Credits":384,
            "Modules codes":["4BOT111","4GES111","4PHY121","4CHM121","4CPS121","4BOT112","4MTH122",
                             "4GES112","4CHM122","4CPS122","4BOT211","4ZOL111","4GES211","4HYD211",
                             "4BOT212","4ZOL112","4HYD222","4BOT311","4BOT331","4BOT312","4BOT322",
                             "4GES312","4GES322"],
            "Modules Names":["INTRODUCTION TO PLANT PHYSIOLOGY & GENETICS","INTRO TO PHYSICAL & ENVIRONMENTAL GEOGRAPHY","CLASSICAL MECHANICS & PROPERTIES OF MATTER(BIO)","BASIC CHEMISTRY 121","COMPUTER LITERACY I","PLANT MORPHOLOGY & TEXONOMY","MATHS & STATS FOR EARTH & LIFE SCIENCES",
                             "HUMAN GEOGRAPHY","BASIC CHEMISTRY 122","COMPUTER LITERACY II","PLANT GROWTH & DEVELOPMENT","INTRO TO ZOOLOGY I","GLOBAL LANDFORMS & CARTOGRAPHY","INTRO TO SURFACE WATER HYDROLOGY","PLANT ANATOMY & BIODIVERSITY","INTRO TO ZOOLOGY II","GEOGRAPHICAL INFORMATION SYSTEMS",
                             "CYTOLOGY GENETICS AND PLANT BIOCHEMISTRY","PLANT ECOPHYSIOLOGY","PEOPLE & PLANTS","PLANT CONSERVATION AND MANAGEMENT & TERRESTRIAL ECOLOGY","ENVIRONMENTAL MANAGEMENT","ENVIRONMENTAL FIELDWORK AND RESEARCH"],
            "Elective module":["DEMOGRAPHICS,HEALTH & SUSTAINABLE DEVELOPMENT","HYDROMETEOROLOGY","URBAN ENVIRONMENT & RECREATION PLANNING","ATMOSPHERIC PROCESSES AND POLLUTION","LAND USE AND NATURAL RESOURCE MANAGEMENT","CLIMATE DYNAMICS & WEATHER VARIABILITY AND PREDICTION"],
            "Elective codes":["4GES212","4GES222","4GES311","4GES321","4GES331","4GES341"]
        },
    "4BSC12":{
            "Departments":["BOTANY","HYDROLOGY"],
            "course name":"BOTANY AND HYDROLOGY",
            "Total Credits":416,
            "Modules codes":["4GES111","4CHM121","4BOT111","4PHY121","4CPS121","4HYD112","4CHM122",
                             "4BOT112","4MTH122","4CPS122","4HYD211","4STT111","4BOT211","4GES211",
                             "4HYD212","4BOT212","4GES222","4HYD222","4HYD311","4HYD321","4BOT311",
                             "4BOT331","4HYD332","4HYD342","4BOT312","4BOT322"],
            "Modules Names":["INTRO TO PHYSICAL & ENVIRONMENTAL GEOGRAPHY","BASIC CHEMISTRY 121","INTRODUCTION TO PLANT PHYSIOLOGY & GENETICS","CLASSICAL MECHANICS & PROPERTIES OF MATTER(BIO)","COMPUTER LITERACY I","INTRO TO GEOLOGY","BASIC CHEMISTRY 122","PLANT MORPHOLOGY & TEXONOMY",
                             "MATHS & STATS FOR EARTH & LIFE SCIENCES","COMPUTER LITERACY II","INTRO TO SURFACE WATER HYDROLOGY","ELEMENTARY STATISTICS FOR SCIENCE STUDENTS","PLANT GROWTH & DEVELOPMENT","GLOBAL LANDFORMS & CARTOGRAPHY","INTRO TO SUBSURFACE HYDROLOGY",
                             "PLANT ANATOMY & BIODIVERSITY","HYDROMETEOROLOGY","GEOGRAPHICAL INFORMATION SYSTEMS","SURFACE WATER HYDROLOGY","GROUNDWATER HYDROLOGY","CYTOLOGY GENETICS AND PLANT BIOCHEMISTRY","PLANT ECOPHYSIOLOGY","HYDROLOGICAL MODELLING","WATER RESOURCES MANAGEMENT",
                             "PEOPLE & PLANTS","PLANT CONSERVATION AND MANAGEMENT & TERRESTRIAL ECOLOGY"],
            "Elective module":[],
            "Elective codes":[]
        },
    "4BSC13":{
            "Departments":["BOTANY","BIOCHEMMISTRY & MICROBIOLOGY"],
            "course name":"BOTANY AND MICROBIOLOGY",
            "Total Credits":416,
            "Modules codes":["4CHM121",
                             "4PHY121",
                             "4BOT111",
                             "4ZOL111",
                             "4CPS121",
                             "4CHM122",
                             "4MTH122",
                             "4BOT112",
                             "4ZOL112",
                             "4CPS122",
                             "4BOT211",
                             "4BCH211",
                             "4MCB221",
                             "4MCB211",
                             "4BOT212",
                             "4BCH212",
                             "4BCH222",
                             "4MCB212",
                             "4BOT311",
                             "4BOT331",
                             "4MCB311",
                             "4MCB321",
                             "4BOT312",
                             "4BOT322",
                             "4MCB312",
                             "4MCB322"],
            "Modules Names":["BASIC CHEMISTRY 121",
                             "CLASSICAL MECHANICS & PROPERTIES OF MATTER(BIO)",
                             "INTRODUCTION TO PLANT PHYSIOLOGY & GENETICS",
                             "INTRO TO ZOOLOGY I",
                             "COMPUTER LITERACY I",
                             "BASIC CHEMISTRY 122",
                             "MATHS & STATS FOR EARTH & LIFE SCIENCES",
                             "PLANT MORPHOLOGY & TEXONOMY",
                             "INTRO TO ZOOLOGY II",
                             "COMPUTER LITERACY II",
                             "PLANT GROWTH & DEVELOPMENT",
                             "BIOMOLECULES & ENZYMOLOGY",
                             "PROKARYOTES STRUCTURE AND ENVIRONMENTAL MICROBIOLOGY",
                             "PROKARYOTES CLASSIFICATION & MICROBIAL TECHNIQUES",
                             "PLANT ANATOMY & BIODIVERSITY",
                             "METABOLISM",
                             "BIOCHEMISTRY: PRINCIPLES & TECHNIQUES",
                             "MICROBIAL GROWTH & MEDICAL MICROBIOLOGY",
                             "CYTOLOGY GENETICS AND PLANT BIOCHEMISTRY",
                             "PLANT ECOPHYSIOLOGY",
                             "FOOD MICROBIOLOGY",
                             "EPIDEMIOLOGY",
                             "PEOPLE & PLANTS",
                             "PLANT CONSERVATION AND MANAGEMENT & TERRESTRIAL ECOLOGY",
                             "ENVIRONMENTAL INFLUENCES ON MICRO-ORGANISMS & INDUSTRIAL MICROBIOLOGY",
                             "BIOTECHNOLOGY"],
            "Elective module":[],
            "Elective codes":[]
        }
}

