

Courses = {

    "4BSC01":{

        "Departments":["Mathematical Science","Computer Scince"],
        "course name":"APPLIED MATHEMATICS AND COMPUTER SCIENCE",
        "Total Credits":416,
        "Module codes":["4AMT111","4MTH111","4CPS111","4CPS121","4AMT122","4MTH112","4CPS112","4CPS122","4AMT211","4MTH221","4CPS211",
                         "4CPS231","4AMT212","4MTH222","4CPS212","4CPS232","4AMT331","4AMT321","4CPS311","4CPS321","4AMT312","4AMT322",
                         "4CPS312","4CPS322"],
        "Module Names":["DISCRETE MATHEMATICS",
                         "CALCULUS I",
                         "INTRODUCTORY COMPUTING",
                         "COMPUTER LITERACY I ",
                         "FURTHER DISCRETE MATHEMATICS",
                         "CALCULUS II ",
                         "INTRO TO SYSTEMS PROGRAMMING",
                         "COMPUTER LITERACY II",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "ADVANCED CALCULUS",
                         "DATA STRUCTURES AND ALGORITHMS",
                         "COMPUTER COMMUNICATIONS & NETWORKS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "SOFTWARE ENGINEERING",
                         "DATABASE INFORMATION MANAGEMENT I",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "ADVANCED PROGRAMMING TECHNIQUES",
                         "SYSTEMS PROGRAMMING (OS & COMPILERS)",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS",
                         "DISTRIBUTED SYSTEMS DEVELOPMENT",
                         "FINAL YEAR PROJECT"],
        "Elective modules":["CLASSICAL MECHANICS & PROPERTIES OF MATTER",
                           " ELEMENTARY STATISTICS FOR SCIENCE STUDENTS",
                           "ELECTROMAGNETISM, NUCLEAR & MODERN PHYSICS",
                           "STATISTICS FOR SCIENCE STUDENTS"],
        "Elective codes":["4PHY111","4STT111","4PHY112","4STT112"]
    },

"4BSC02":{
        "Departments":["MATHEMATICAL SCIENCES","HYDROLOGY"],
        "course name":"APPLIED MATHEMATICS AND HYDROLOGY",
        "Total Credits":416,
        "Module codes":["4GES111","4MTH111","4AMT111","4PHY111","4CPS121","4HYD112","4MTH112","4AMT122","4STT122","4CPS122",
                         "4HYD211","4MTH221","4AMT211","4GES211","4HYD212","4MTH222","4AMT212","4HYD222",
                         "4HYD311","4HYD321","4AMT331","4AMT321","4HYD332","4HYD342","4AMT312","4AMT322"],
        "Module Names":["INTRO TO PHYSICAL & ENVIRONMENTAL GEOGRAPHY",
                         "CALCULUS I",
                         "DISCRETE MATHEMATICS",
                         "CLASSICAL MECHANICS AND PROPERTIES OF MATTER",
                         "COMPUTER LITERACY I",
                         "INTRO TO GEOLOGY",
                         "CALCULUS II",
                         "FURTHER DISCRETE MATHEMATICS",
                         "ELEMENTARY STATISTICS FOR COMMERCE STUDENTS",
                         "COMPUTER LITERACY II",
                         "INTRO TO SURFACE WATER HYDROLOGY",
                         "ADVANCED CALCULUS",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "GLOBAL LANDFORMS & CARTOGRAPHY",
                         "INTRO TO SUBSURFACE HYDROLOGY",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "GEOGRAPHICAL INFORMATION SYSTEMS",
                         "SURFACE WATER HYDROLOGY",
                         "GROUNDWATER HYDROLOGY",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "HYDROLOGICAL MODELLING",
                         "WATER RESOURCES MANAGEMENT",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS"],
        "Elective modules":[],
        "Elective codes":[]
    },
"4BSC03":{
        "Departments":["MATHEMATICAL SCIENCES"],
        "course name":"APPLIED MATHEMATICS AND MATHEMATICS",
        "Total Credits":416,
        "Module codes":["4MTH111","4AMT111","4CPS121","4AMT122","4MTH112","4CPS112",
                         "4CPS122","4AMT211","4MTH221","4AMT212","4MTH222","4AMT331",
                         "4AMT321","4MTH311","4MTH321","4AMT312","4AMT322","4MTH312","4MTH322"],
        "Module Names":["CALCULUS I",
                         "DISCRETE MATHEMATICS",
                         "COMPUTER LITERACY I",
                         "FURTHER DISCRETE MATHEMATICS",
                         "CALCULUS II",
                         "INTRO TO SYSTEMS PROGRAMMING",
                         "COMPUTER LITERACY II",
                         "DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING",
                         "ADVANCED CALCULUS",
                         "INTRO TO OPERATIONS RESEARCH",
                         "LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS",
                         "TENSOR ANALYSIS",
                         "APPLIED MATHEMATICAL METHODS",
                         "ABSTRACT ALGEBRA",
                         "REAL ANALYSIS",
                         "ADVANCED CLASSICAL MECHANICS",
                         "NUMERICAL METHODS",
                         "GRAPH THEORY",
                         "COMPLEX ANALYSIS"],
        "Elective modules":["INTRODUCTORY COMPUTING",
                           "CLASSICAL MECHANICS & MECHANICS & PROPERTIES OF MATTER",
                           "GENERAL CHEMISTRY 111",
                            "ELECTROMAGNETISM,NUCLEAR & MODERN PHYSICS",
                          "GENERAL CHEMISTRY 112",
                          "DATA STRUCTURES AND ALGORITHMS",
                          "MECHANICS SPECIAL RELATIVITY & PROPERTIES OF MATTER",
                          "DISTRIBUTION THEORY",
                          "COMPUTER COMMUNICATIONS NETWORKS",
                          "ANALYTICAL & INORGANIC CHEMISTRY 2",
                          "SOFTWARE ENGINEERING",
                          "MODERN PHYSICS,PHOTONICS AND WAVES",
                          "DATABASE INFORMATION MANAGEMENT I",
                          "ORGANIC & PHYSICAL CHEMISTRY 2"],
        "Elective codes":["4CPS111","4PHY111","4CHM111","4PHY112","4CHM112","4CPS211","4PHY211","4STT211","4CPS231","4CHM211","4CPS212","4PHY212","4CPS232","4CHM212"]
    },
"4BSC04":{
        "Departments":["MATHEMATICAL SCIENCES","PHYSICS & ENGINEERING"],
        "course name":"APPLIED MATHEMATICS AND PHYSICS",
        "Total Credits":416,
        "Modules codes":["4MTH111","4AMT111","4PHY111","4CPS121","4AMT122","4MTH112","4PHY112",
                         "4CPS122","4AMT211","4MTH221","4PHY211","4AMT212","4MTH222","4PHY212",
                         "4PHY222","4AMT331","4AMT321","4PHY311","4PHY321","4AMT312","4AMT322",
                         "4PHY312","4PHY322"],
        "Modules Names":["CALCULUS I","DISCRETE MATHEMATICS","CLASSICAL MECHANICS & PROPERTIES OF MATTER","COMPUTER LITERACY I","FURTHER DISCRETE MATHEMATICS","CALCULUS II ",
                         "ELECTROMAGNETISM, NUCLEAR & MODERN PHYSICS","COMPUTER LITERACY II ","DYNAMICAL SYSTEMS & MATHEMATICAL MODELLING","ADVANCED CALCULUS","MECHANICS SPECIAL RELATIVITY & PROPERTIES OF MATTER",
                         "INTRO TO OPERATIONS RESEARCH","LINEAR ALGEBRA & DIFFERENTIAL EQUATIONS","MODERN PHYSICS, PHOTONICS & WAVES","ELECTROMAGNETISM","TENSOR ANALYSIS","APPLIED MATHEMATICAL METHODS","QUANTUM AND STATISTICAL PHYSICS",
                         "ELECTRONIC CIRCUITS AND DEVICES","ADVANCED CLASSICAL MECHANICS","NUMERICAL METHODS ","NUCLEAR PHYSICS AND APPLICATIONS","SOLID STATE PHYSICS & MATERIAL SCIENCE"],
        "Elective modules":["INTRODUCTORY COMPUTING","GENERAL CHEMISTRY 111","INTRO TO SYSTEMS PROGRAMMING","ANALYTICAL & INORGANIC CHEMISTRY 2","DATA STRUCTURES AND ALGORITHMS","ANALYTICAL & INORGANIC CHEMISTRY 2"],
        "Elective codes":["4CPS111","4CHM111","4CPS112","4CHM112","4CPS211","4CHM211"]

    }
}

